// Code generated by "validate -type=bool -output=%s_generated.go"; DO NOT EDIT

package validate

import "text/template"

type BoolValidator struct {
	errorMessage string
	params       map[string]interface{}
	validate     func(bool) bool

	constParams map[string]interface{}
	validators  []func(bool) error
}

func NewBoolValidator(params map[string]interface{}) *BoolValidator {
	return &BoolValidator{constParams: params}
}

func (validator *BoolValidator) Validate(validate func(bool) bool) *BoolValidator {
	validator.validate = validate
	return validator
}

func (validator *BoolValidator) WithParams(params map[string]interface{}) *BoolValidator {
	validator.params = params
	return validator
}

func (validator *BoolValidator) WithErrorMessage(errorMessage string) *BoolValidator {
	validator.errorMessage = errorMessage
	return validator
}
func (validator *BoolValidator) Add() *BoolValidator {
	if validator.validate != nil {
		tmpl := template.Must(template.New("errorMessage").Parse(validator.errorMessage))
		params := make(map[string]interface{})
		for key, value := range validator.constParams {
			params[key] = value
		}
		for key, value := range validator.params {
			params[key] = value
		}
		isValid := validator.validate
		validator.validators = append(validator.validators,
			func(value bool) error {
				if isValid(value) {
					return nil
				}
				return FormatErrorMessage(tmpl, params, value)
			})
	}
	validator.errorMessage = ""
	validator.params = nil
	return validator
}

func (validator *BoolValidator) Build() func(bool) error {
	validator.Add()
	validators := validator.validators
	return func(value bool) error {
		for _, validate := range validators {
			if err := validate(value); err != nil {
				return err
			}
		}
		return nil
	}
}

func (validator *BoolValidator) NonZero() *BoolValidator {
	var zero bool
	return validator.Add().Validate(func(value bool) bool { return value != zero }).WithErrorMessage("{.Value} must not be a zero value")
}
