// Code generated by "validate -type=byte -output=%s_generated.go"; DO NOT EDIT

package validate

import "text/template"

type ByteValidator struct {
	errorMessage string
	params       map[string]interface{}
	validate     func(byte) bool

	constParams map[string]interface{}
	validators  []func(byte) error
}

func NewByteValidator(params map[string]interface{}) *ByteValidator {
	return &ByteValidator{constParams: params}
}

func (validator *ByteValidator) Validate(validate func(byte) bool) *ByteValidator {
	validator.validate = validate
	return validator
}

func (validator *ByteValidator) WithParams(params map[string]interface{}) *ByteValidator {
	validator.params = params
	return validator
}

func (validator *ByteValidator) WithErrorMessage(errorMessage string) *ByteValidator {
	validator.errorMessage = errorMessage
	return validator
}
func (validator *ByteValidator) Add() *ByteValidator {
	if validator.validate != nil {
		tmpl := template.Must(template.New("errorMessage").Parse(validator.errorMessage))
		params := make(map[string]interface{})
		for key, value := range validator.constParams {
			params[key] = value
		}
		for key, value := range validator.params {
			params[key] = value
		}
		isValid := validator.validate
		validator.validators = append(validator.validators,
			func(value byte) error {
				if isValid(value) {
					return nil
				}
				return FormatErrorMessage(tmpl, params, value)
			})
	}
	validator.errorMessage = ""
	validator.params = nil
	return validator
}

func (validator *ByteValidator) Build() func(byte) error {
	validator.Add()
	validators := validator.validators
	return func(value byte) error {
		for _, validate := range validators {
			if err := validate(value); err != nil {
				return err
			}
		}
		return nil
	}
}

func (validator *ByteValidator) NonZero() *ByteValidator {
	var zero byte
	return validator.Add().Validate(func(value byte) bool { return value != zero }).WithErrorMessage("{.Value} must not be a zero value")
}

func (validator *ByteValidator) Min(min byte) *ByteValidator {
	return validator.Add().Validate(func(value byte) bool { return value >= min }).
		WithParams(map[string]interface{}{"MinValue": min}).
		WithErrorMessage("{.Value} must be greater than or equal to {.MinValue}")
}

func (validator *ByteValidator) Max(max byte) *ByteValidator {
	return validator.Add().Validate(func(value byte) bool { return value <= max }).
		WithParams(map[string]interface{}{"MaxValue": max}).
		WithErrorMessage("{.Value} must be less than or equal to {.MaxValue}")
}

func (validator *ByteValidator) Between(min, max byte) *ByteValidator {
	return validator.Add().Validate(func(value byte) bool { return value >= min && value <= max }).
		WithParams(map[string]interface{}{"MinValue": min, "MaxValue": max}).
		WithErrorMessage("{.Value} must be between {.MinValue} and {.MaxValue}")
}
