// Code generated by "validate -type=complex64 -output=%s_generated.go"; DO NOT EDIT

package validate

import "text/template"

type Complex64Validator struct {
	errorMessage string
	params       map[string]interface{}
	validate     func(complex64) bool

	constParams map[string]interface{}
	validators  []func(complex64) error
}

func NewComplex64Validator(params map[string]interface{}) *Complex64Validator {
	return &Complex64Validator{constParams: params}
}

func (validator *Complex64Validator) Validate(validate func(complex64) bool) *Complex64Validator {
	validator.validate = validate
	return validator
}

func (validator *Complex64Validator) WithParams(params map[string]interface{}) *Complex64Validator {
	validator.params = params
	return validator
}

func (validator *Complex64Validator) WithErrorMessage(errorMessage string) *Complex64Validator {
	validator.errorMessage = errorMessage
	return validator
}
func (validator *Complex64Validator) Add() *Complex64Validator {
	if validator.validate != nil {
		tmpl := template.Must(template.New("errorMessage").Parse(validator.errorMessage))
		params := make(map[string]interface{})
		for key, value := range validator.constParams {
			params[key] = value
		}
		for key, value := range validator.params {
			params[key] = value
		}
		isValid := validator.validate
		validator.validators = append(validator.validators,
			func(value complex64) error {
				if isValid(value) {
					return nil
				}
				return FormatErrorMessage(tmpl, params, value)
			})
	}
	validator.errorMessage = ""
	validator.params = nil
	return validator
}

func (validator *Complex64Validator) Build() func(complex64) error {
	validator.Add()
	validators := validator.validators
	return func(value complex64) error {
		for _, validate := range validators {
			if err := validate(value); err != nil {
				return err
			}
		}
		return nil
	}
}

func (validator *Complex64Validator) NonZero() *Complex64Validator {
	var zero complex64
	return validator.Add().Validate(func(value complex64) bool { return value != zero }).WithErrorMessage("{.Value} must not be a zero value")
}
