// Code generated by "validate -type=int32 -output=%s_generated.go"; DO NOT EDIT

package validate

import "text/template"

type Int32Validator struct {
	errorMessage string
	params       map[string]interface{}
	validate     func(int32) bool

	constParams map[string]interface{}
	validators  []func(int32) error
}

func NewInt32Validator(params map[string]interface{}) *Int32Validator {
	return &Int32Validator{constParams: params}
}

func (validator *Int32Validator) Validate(validate func(int32) bool) *Int32Validator {
	validator.validate = validate
	return validator
}

func (validator *Int32Validator) WithParams(params map[string]interface{}) *Int32Validator {
	validator.params = params
	return validator
}

func (validator *Int32Validator) WithErrorMessage(errorMessage string) *Int32Validator {
	validator.errorMessage = errorMessage
	return validator
}
func (validator *Int32Validator) Add() *Int32Validator {
	if validator.validate != nil {
		tmpl := template.Must(template.New("errorMessage").Parse(validator.errorMessage))
		params := make(map[string]interface{})
		for key, value := range validator.constParams {
			params[key] = value
		}
		for key, value := range validator.params {
			params[key] = value
		}
		isValid := validator.validate
		validator.validators = append(validator.validators,
			func(value int32) error {
				if isValid(value) {
					return nil
				}
				return FormatErrorMessage(tmpl, params, value)
			})
	}
	validator.errorMessage = ""
	validator.params = nil
	return validator
}

func (validator *Int32Validator) Build() func(int32) error {
	validator.Add()
	validators := validator.validators
	return func(value int32) error {
		for _, validate := range validators {
			if err := validate(value); err != nil {
				return err
			}
		}
		return nil
	}
}

func (validator *Int32Validator) NonZero() *Int32Validator {
	var zero int32
	return validator.Add().Validate(func(value int32) bool { return value != zero }).WithErrorMessage("{.Value} must not be a zero value")
}

func (validator *Int32Validator) Min(min int32) *Int32Validator {
	return validator.Add().Validate(func(value int32) bool { return value >= min }).
		WithParams(map[string]interface{}{"MinValue": min}).
		WithErrorMessage("{.Value} must be greater than or equal to {.MinValue}")
}

func (validator *Int32Validator) Max(max int32) *Int32Validator {
	return validator.Add().Validate(func(value int32) bool { return value <= max }).
		WithParams(map[string]interface{}{"MaxValue": max}).
		WithErrorMessage("{.Value} must be less than or equal to {.MaxValue}")
}

func (validator *Int32Validator) Between(min, max int32) *Int32Validator {
	return validator.Add().Validate(func(value int32) bool { return value >= min && value <= max }).
		WithParams(map[string]interface{}{"MinValue": min, "MaxValue": max}).
		WithErrorMessage("{.Value} must be between {.MinValue} and {.MaxValue}")
}
