// Code generated by "validate -type=int8 -output=%s_generated.go"; DO NOT EDIT

package validate

import "text/template"

type Int8Validator struct {
	errorMessage string
	params       map[string]interface{}
	validate     func(int8) bool

	constParams map[string]interface{}
	validators  []func(int8) error
}

func NewInt8Validator(params map[string]interface{}) *Int8Validator {
	return &Int8Validator{constParams: params}
}

func (validator *Int8Validator) Validate(validate func(int8) bool) *Int8Validator {
	validator.validate = validate
	return validator
}

func (validator *Int8Validator) WithParams(params map[string]interface{}) *Int8Validator {
	validator.params = params
	return validator
}

func (validator *Int8Validator) WithErrorMessage(errorMessage string) *Int8Validator {
	validator.errorMessage = errorMessage
	return validator
}
func (validator *Int8Validator) Add() *Int8Validator {
	if validator.validate != nil {
		tmpl := template.Must(template.New("errorMessage").Parse(validator.errorMessage))
		params := make(map[string]interface{})
		for key, value := range validator.constParams {
			params[key] = value
		}
		for key, value := range validator.params {
			params[key] = value
		}
		isValid := validator.validate
		validator.validators = append(validator.validators,
			func(value int8) error {
				if isValid(value) {
					return nil
				}
				return FormatErrorMessage(tmpl, params, value)
			})
	}
	validator.errorMessage = ""
	validator.params = nil
	return validator
}

func (validator *Int8Validator) Build() func(int8) error {
	validator.Add()
	validators := validator.validators
	return func(value int8) error {
		for _, validate := range validators {
			if err := validate(value); err != nil {
				return err
			}
		}
		return nil
	}
}

func (validator *Int8Validator) NonZero() *Int8Validator {
	var zero int8
	return validator.Add().Validate(func(value int8) bool { return value != zero }).WithErrorMessage("{.Value} must not be a zero value")
}

func (validator *Int8Validator) Min(min int8) *Int8Validator {
	return validator.Add().Validate(func(value int8) bool { return value >= min }).
		WithParams(map[string]interface{}{"MinValue": min}).
		WithErrorMessage("{.Value} must be greater than or equal to {.MinValue}")
}

func (validator *Int8Validator) Max(max int8) *Int8Validator {
	return validator.Add().Validate(func(value int8) bool { return value <= max }).
		WithParams(map[string]interface{}{"MaxValue": max}).
		WithErrorMessage("{.Value} must be less than or equal to {.MaxValue}")
}

func (validator *Int8Validator) Between(min, max int8) *Int8Validator {
	return validator.Add().Validate(func(value int8) bool { return value >= min && value <= max }).
		WithParams(map[string]interface{}{"MinValue": min, "MaxValue": max}).
		WithErrorMessage("{.Value} must be between {.MinValue} and {.MaxValue}")
}
