// Code generated by "validate -type=int -output=%s_generated.go"; DO NOT EDIT

package validate

import "text/template"

type IntValidator struct {
	errorMessage string
	params       map[string]interface{}
	validate     func(int) bool

	constParams map[string]interface{}
	validators  []func(int) error
}

func NewIntValidator(params map[string]interface{}) *IntValidator {
	return &IntValidator{constParams: params}
}

func (validator *IntValidator) Validate(validate func(int) bool) *IntValidator {
	validator.validate = validate
	return validator
}

func (validator *IntValidator) WithParams(params map[string]interface{}) *IntValidator {
	validator.params = params
	return validator
}

func (validator *IntValidator) WithErrorMessage(errorMessage string) *IntValidator {
	validator.errorMessage = errorMessage
	return validator
}
func (validator *IntValidator) Add() *IntValidator {
	if validator.validate != nil {
		tmpl := template.Must(template.New("errorMessage").Parse(validator.errorMessage))
		params := make(map[string]interface{})
		for key, value := range validator.constParams {
			params[key] = value
		}
		for key, value := range validator.params {
			params[key] = value
		}
		isValid := validator.validate
		validator.validators = append(validator.validators,
			func(value int) error {
				if isValid(value) {
					return nil
				}
				return FormatErrorMessage(tmpl, params, value)
			})
	}
	validator.errorMessage = ""
	validator.params = nil
	return validator
}

func (validator *IntValidator) Build() func(int) error {
	validator.Add()
	validators := validator.validators
	return func(value int) error {
		for _, validate := range validators {
			if err := validate(value); err != nil {
				return err
			}
		}
		return nil
	}
}

func (validator *IntValidator) NonZero() *IntValidator {
	var zero int
	return validator.Add().Validate(func(value int) bool { return value != zero }).WithErrorMessage("{.Value} must not be a zero value")
}

func (validator *IntValidator) Min(min int) *IntValidator {
	return validator.Add().Validate(func(value int) bool { return value >= min }).
		WithParams(map[string]interface{}{"MinValue": min}).
		WithErrorMessage("{.Value} must be greater than or equal to {.MinValue}")
}

func (validator *IntValidator) Max(max int) *IntValidator {
	return validator.Add().Validate(func(value int) bool { return value <= max }).
		WithParams(map[string]interface{}{"MaxValue": max}).
		WithErrorMessage("{.Value} must be less than or equal to {.MaxValue}")
}

func (validator *IntValidator) Between(min, max int) *IntValidator {
	return validator.Add().Validate(func(value int) bool { return value >= min && value <= max }).
		WithParams(map[string]interface{}{"MinValue": min, "MaxValue": max}).
		WithErrorMessage("{.Value} must be between {.MinValue} and {.MaxValue}")
}
