// Code generated by "validate -type=string -output=%s_generated.go"; DO NOT EDIT

package validate

import "text/template"

type StringValidator struct {
	errorMessage string
	params       map[string]interface{}
	validate     func(string) bool

	constParams map[string]interface{}
	validators  []func(string) error
}

func NewStringValidator(params map[string]interface{}) *StringValidator {
	return &StringValidator{constParams: params}
}

func (validator *StringValidator) Validate(validate func(string) bool) *StringValidator {
	validator.validate = validate
	return validator
}

func (validator *StringValidator) WithParams(params map[string]interface{}) *StringValidator {
	validator.params = params
	return validator
}

func (validator *StringValidator) WithErrorMessage(errorMessage string) *StringValidator {
	validator.errorMessage = errorMessage
	return validator
}
func (validator *StringValidator) Add() *StringValidator {
	if validator.validate != nil {
		tmpl := template.Must(template.New("errorMessage").Parse(validator.errorMessage))
		params := make(map[string]interface{})
		for key, value := range validator.constParams {
			params[key] = value
		}
		for key, value := range validator.params {
			params[key] = value
		}
		isValid := validator.validate
		validator.validators = append(validator.validators,
			func(value string) error {
				if isValid(value) {
					return nil
				}
				return FormatErrorMessage(tmpl, params, value)
			})
	}
	validator.errorMessage = ""
	validator.params = nil
	return validator
}

func (validator *StringValidator) Build() func(string) error {
	validator.Add()
	validators := validator.validators
	return func(value string) error {
		for _, validate := range validators {
			if err := validate(value); err != nil {
				return err
			}
		}
		return nil
	}
}

func (validator *StringValidator) NonZero() *StringValidator {
	var zero string
	return validator.Add().Validate(func(value string) bool { return value != zero }).WithErrorMessage("{.Value} must not be a zero value")
}
