// Code generated by "validate -type=uint64 -output=%s_generated.go"; DO NOT EDIT

package validate

import "text/template"

type Uint64Validator struct {
	errorMessage string
	params       map[string]interface{}
	validate     func(uint64) bool

	constParams map[string]interface{}
	validators  []func(uint64) error
}

func NewUint64Validator(params map[string]interface{}) *Uint64Validator {
	return &Uint64Validator{constParams: params}
}

func (validator *Uint64Validator) Validate(validate func(uint64) bool) *Uint64Validator {
	validator.validate = validate
	return validator
}

func (validator *Uint64Validator) WithParams(params map[string]interface{}) *Uint64Validator {
	validator.params = params
	return validator
}

func (validator *Uint64Validator) WithErrorMessage(errorMessage string) *Uint64Validator {
	validator.errorMessage = errorMessage
	return validator
}
func (validator *Uint64Validator) Add() *Uint64Validator {
	if validator.validate != nil {
		tmpl := template.Must(template.New("errorMessage").Parse(validator.errorMessage))
		params := make(map[string]interface{})
		for key, value := range validator.constParams {
			params[key] = value
		}
		for key, value := range validator.params {
			params[key] = value
		}
		isValid := validator.validate
		validator.validators = append(validator.validators,
			func(value uint64) error {
				if isValid(value) {
					return nil
				}
				return FormatErrorMessage(tmpl, params, value)
			})
	}
	validator.errorMessage = ""
	validator.params = nil
	return validator
}

func (validator *Uint64Validator) Build() func(uint64) error {
	validator.Add()
	validators := validator.validators
	return func(value uint64) error {
		for _, validate := range validators {
			if err := validate(value); err != nil {
				return err
			}
		}
		return nil
	}
}

func (validator *Uint64Validator) NonZero() *Uint64Validator {
	var zero uint64
	return validator.Add().Validate(func(value uint64) bool { return value != zero }).WithErrorMessage("{.Value} must not be a zero value")
}

func (validator *Uint64Validator) Min(min uint64) *Uint64Validator {
	return validator.Add().Validate(func(value uint64) bool { return value >= min }).
		WithParams(map[string]interface{}{"MinValue": min}).
		WithErrorMessage("{.Value} must be greater than or equal to {.MinValue}")
}

func (validator *Uint64Validator) Max(max uint64) *Uint64Validator {
	return validator.Add().Validate(func(value uint64) bool { return value <= max }).
		WithParams(map[string]interface{}{"MaxValue": max}).
		WithErrorMessage("{.Value} must be less than or equal to {.MaxValue}")
}

func (validator *Uint64Validator) Between(min, max uint64) *Uint64Validator {
	return validator.Add().Validate(func(value uint64) bool { return value >= min && value <= max }).
		WithParams(map[string]interface{}{"MinValue": min, "MaxValue": max}).
		WithErrorMessage("{.Value} must be between {.MinValue} and {.MaxValue}")
}
