// Code generated by "validate -type=uint32 -output=%s_generated.go"; DO NOT EDIT

package validate

import "text/template"

type Uint32Validator struct {
	errorMessage string
	params       map[string]interface{}
	validate     func(uint32) bool

	constParams map[string]interface{}
	validators  []func(uint32) error
}

func NewUint32Validator(params map[string]interface{}) *Uint32Validator {
	return &Uint32Validator{constParams: params}
}

func (validator *Uint32Validator) Validate(validate func(uint32) bool) *Uint32Validator {
	validator.validate = validate
	return validator
}

func (validator *Uint32Validator) WithParams(params map[string]interface{}) *Uint32Validator {
	validator.params = params
	return validator
}

func (validator *Uint32Validator) WithErrorMessage(errorMessage string) *Uint32Validator {
	validator.errorMessage = errorMessage
	return validator
}
func (validator *Uint32Validator) Add() *Uint32Validator {
	if validator.validate != nil {
		tmpl := template.Must(template.New("errorMessage").Parse(validator.errorMessage))
		params := make(map[string]interface{})
		for key, value := range validator.constParams {
			params[key] = value
		}
		for key, value := range validator.params {
			params[key] = value
		}
		isValid := validator.validate
		validator.validators = append(validator.validators,
			func(value uint32) error {
				if isValid(value) {
					return nil
				}
				return FormatErrorMessage(tmpl, params, value)
			})
	}
	validator.errorMessage = ""
	validator.params = nil
	return validator
}

func (validator *Uint32Validator) Build() func(uint32) error {
	validator.Add()
	validators := validator.validators
	return func(value uint32) error {
		for _, validate := range validators {
			if err := validate(value); err != nil {
				return err
			}
		}
		return nil
	}
}

func (validator *Uint32Validator) NonZero() *Uint32Validator {
	var zero uint32
	return validator.Add().Validate(func(value uint32) bool { return value != zero }).WithErrorMessage("{.Value} must not be a zero value")
}

func (validator *Uint32Validator) Min(min uint32) *Uint32Validator {
	return validator.Add().Validate(func(value uint32) bool { return value >= min }).
		WithParams(map[string]interface{}{"MinValue": min}).
		WithErrorMessage("{.Value} must be greater than or equal to {.MinValue}")
}

func (validator *Uint32Validator) Max(max uint32) *Uint32Validator {
	return validator.Add().Validate(func(value uint32) bool { return value <= max }).
		WithParams(map[string]interface{}{"MaxValue": max}).
		WithErrorMessage("{.Value} must be less than or equal to {.MaxValue}")
}

func (validator *Uint32Validator) Between(min, max uint32) *Uint32Validator {
	return validator.Add().Validate(func(value uint32) bool { return value >= min && value <= max }).
		WithParams(map[string]interface{}{"MinValue": min, "MaxValue": max}).
		WithErrorMessage("{.Value} must be between {.MinValue} and {.MaxValue}")
}
