// Code generated by "validate -type=uint -output=%s_generated.go"; DO NOT EDIT

package validate

import "text/template"

type UintValidator struct {
	errorMessage string
	params       map[string]interface{}
	validate     func(uint) bool

	constParams map[string]interface{}
	validators  []func(uint) error
}

func NewUintValidator(params map[string]interface{}) *UintValidator {
	return &UintValidator{constParams: params}
}

func (validator *UintValidator) Validate(validate func(uint) bool) *UintValidator {
	validator.validate = validate
	return validator
}

func (validator *UintValidator) WithParams(params map[string]interface{}) *UintValidator {
	validator.params = params
	return validator
}

func (validator *UintValidator) WithErrorMessage(errorMessage string) *UintValidator {
	validator.errorMessage = errorMessage
	return validator
}
func (validator *UintValidator) Add() *UintValidator {
	if validator.validate != nil {
		tmpl := template.Must(template.New("errorMessage").Parse(validator.errorMessage))
		params := make(map[string]interface{})
		for key, value := range validator.constParams {
			params[key] = value
		}
		for key, value := range validator.params {
			params[key] = value
		}
		isValid := validator.validate
		validator.validators = append(validator.validators,
			func(value uint) error {
				if isValid(value) {
					return nil
				}
				return FormatErrorMessage(tmpl, params, value)
			})
	}
	validator.errorMessage = ""
	validator.params = nil
	return validator
}

func (validator *UintValidator) Build() func(uint) error {
	validator.Add()
	validators := validator.validators
	return func(value uint) error {
		for _, validate := range validators {
			if err := validate(value); err != nil {
				return err
			}
		}
		return nil
	}
}

func (validator *UintValidator) NonZero() *UintValidator {
	var zero uint
	return validator.Add().Validate(func(value uint) bool { return value != zero }).WithErrorMessage("{.Value} must not be a zero value")
}

func (validator *UintValidator) Min(min uint) *UintValidator {
	return validator.Add().Validate(func(value uint) bool { return value >= min }).
		WithParams(map[string]interface{}{"MinValue": min}).
		WithErrorMessage("{.Value} must be greater than or equal to {.MinValue}")
}

func (validator *UintValidator) Max(max uint) *UintValidator {
	return validator.Add().Validate(func(value uint) bool { return value <= max }).
		WithParams(map[string]interface{}{"MaxValue": max}).
		WithErrorMessage("{.Value} must be less than or equal to {.MaxValue}")
}

func (validator *UintValidator) Between(min, max uint) *UintValidator {
	return validator.Add().Validate(func(value uint) bool { return value >= min && value <= max }).
		WithParams(map[string]interface{}{"MinValue": min, "MaxValue": max}).
		WithErrorMessage("{.Value} must be between {.MinValue} and {.MaxValue}")
}
